### ISSUE TITLE
Load icons asynchronously?

### ISSUE THREAD

**Issue by D3SOX** [mallowigi/a-file-icon-web#124]
**Is your feature request related to a problem? Please describe.**
When browsing repositories with many files in them, it significantly increases the time it needs to load.

**Describe the solution you'd like**
Show the GitHub icons first, then load the custom icons asynchronously in the background.

**Describe alternatives you've considered**
Somehow preloading the icons?

**Additional context**
I'm not sure if it has something to do with the Firefox version of the add-on. I'll have to double-check if the performance impact is also that big in Chromium based browsers.

**Comment by jkowalleck** [comment]
>  When browsing repositories with many files in them, it significantly increases the time it needs to load.

Could you provide an example URL of such a page?

**Comment by D3SOX** [comment]
@jkowalleck It only seems to happen when browsing from one folder to another.

For example, try visiting https://github.com/bikass/kora/tree/master/kora/actions then click on symbolic

When loading https://github.com/bikass/kora/tree/master/kora/actions/symbolic directly, it does not produce any lag for me.

Recording showing the behavior (in a clean Firefox profile):

https://user-images.githubusercontent.com/24937357/165186354-c7ad4e6b-190b-48eb-a0c5-b71dab75e15e.mp4

**Comment by mallowigi** [comment]
Interesting, I knew about such an issue but I didn't think it was caused by the extension. I'll look into it.
