### ISSUE TITLE
Slowness when too many files

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/a-file-icon-web#224]
https://github.com/DynamicYield/adm-icons/tree/master/src/icons see here

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

**Comment by BlockyTheDev** [comment]
Is there anything that can be done to speed it up from the extension side? When using in in my installed Chrome browser it sometimes takes up to 3 seconds while opening THIS repository until the extension icons are displayed. [When using the alternative extension (https://github.com/dderevjanik/github-vscode-icons), which isn't further in active development, it is loading in a time < 0.5 seconds on my side.]

**Comment by mallowigi** [comment]
That was the solution I came with to fix the previous one, which was synchronously loading all icons before rendering, causing freezes when there were too many icons. Delaying it alleviated the issue but as a result, it introduced a delay before seeing the icons.

The vscode icons is doing a mix of that, e.g. loading the first N icons then loading the rest later. But it's too much work for something I take as a side project.

Be my guest if you want to try helping ;)
