### ISSUE TITLE
Enterprise github support

### ISSUE THREAD

**Issue by stychu** [mallowigi/a-file-icon-web#6]
Would it be possible for this extension to support custom enterprise GitHub?? Love the icons on the default but would like also to add the touch to the enterprise GitHub I use for work.

**Comment by mallowigi** [comment]
I don't have an enterprise github so I'm afraid I won't be able to do it.

**Comment by bskiefer** [comment]
Could there be an options page to add custom domains? I'm just building from source with my enterprise URL included right now.

**Comment by mallowigi** [comment]
No, it's not possible as Chrome explicitely requires domain names to run on, and I don't want to add the wildcard *

**Comment by mallowigi** [comment]
But you can simply download this repo and modify the manifest to suit your needs
