### ISSUE TITLE
Update Firefox add-on to 3.0.0

### ISSUE THREAD

**Issue by D3SOX** [mallowigi/a-file-icon-web#78]
It's been some time since 3.0.0 was released, but the Firefox add-on version is still at 2.0.3. So I just wanted to ask if the Firefox version will be updated as well.

**Comment by mallowigi** [comment]
I'll try to find the time to do it, Firefox is a bit more complicated since they need the whole source code to audit before approving updates, so it's a bit of pain to do. But I'll do it eventually.

**Comment by mallowigi** [comment]
TODO: need to improve rollup to avoid including the json in the bundle.js

**Comment by D3SOX** [comment]
![image](https://user-images.githubusercontent.com/24937357/148089782-e873d2e2-132e-449f-a827-53761f02db98.png)
I just received the update. Thank you!
